eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:5700/eureka/
    register-with-eureka: true
    fetch-registry: false
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
test:
  t1:
    t1v: value11111
